### ISSUE TITLE
Configuración SMTP para el envío del correo de bienvenida

### ISSUE THREAD

**Issue by achamorro-dev** [python-spain/symposion#3]
Actualmente estoy pendiente de hablar con Jesus Cea para ver si nos hace el favorcete de configurar el server SMTP de PyConES. Si no, tocara que nos redireccione el dominio y ver donde hacerlo :)

**Comment by astrojuanlu** [comment]
En realidad el dominio creo que va aparte ¿no? Es decir, podríamos usar su SMTP sin hacer el cambio de DNS. Pero sí, en cuanto el envío de correo funcione y los detalles estén pulidos podremos lanzar la web :)
